### ISSUE TITLE
Typesetters are not presented with the figure files

### ISSUE THREAD

**Issue by mauromsl** [BirkbeckCTP/typesetting#129]
During the typesetting assignment form, we tell the editor that the typesetter will have access to all figures and supplementary files. This is not the case, they only have access to the manuscript files selected by the editor

**Comment by ajrbyers** [comment]
Actually its currently the opposite. We tell the editor to include all images but infact give the typesetter access to them automatically.

**Comment by joemull** [comment]
Adding to 1.6 @ajrbyers -- OK?
