### ISSUE TITLE
Proofing instruction text

### ISSUE THREAD

**Issue by joemull** [BirkbeckCTP/typesetting#133]
Two issues that might be related:

1. As production manager, the text I type into the "Proofing Task" (Screenshot 1) to give the proofreader (in this case Example Editor) instructions does not appear anywhere when I log in to view the proofing task as Example Editor (Screenshot 2).
2. As journal admin manager, I'd like to be able to change the text that appears on the proofreading assignment page in the first main box (Screenshot 2).

Being able to use these two things in concert will help me communicate clearly with proofreaders about logistics.

Thanks!
![Screenshot 1](https://user-images.githubusercontent.com/47217308/118861931-110e4b80-b8ab-11eb-9446-9e5400f941e5.png)
![Screenshot 2](https://user-images.githubusercontent.com/47217308/118861936-11a6e200-b8ab-11eb-8e09-190db9d44c6b.png)

**Comment by mauromsl** [comment]
Thanks for the report @joemull 
We've added back in the "task" text entered by the editor so it should render in the proofreading page now.
The default text that shows the instructions is stored under a setting that you can edit on a per journal basis or from the press manager for all journals. It is called "Proofreader Guide (PLUGIN)":
![image](https://user-images.githubusercontent.com/10760678/119873374-61755100-bf1c-11eb-99e0-ec707174b6e3.png)

closed by 4d059f462eff88e9a9397859eb6d8d27ba7047e6

**Comment by joemull** [comment]
Thanks @mauromsl ! We really appreciate this. Just checked it out, and everything works as you said.
