### ISSUE TITLE
'Manage typesetting' option not always available

### ISSUE THREAD

**Issue by mauromsl** [BirkbeckCTP/typesetting#134]
I believe we removed this link under certain scenarios (e.g when the typesetter/proofreader is actively working on an assigned task to avoid having simultaneous updates)

However this impedes the editor from reviewing what was requested.

Instead we should still present a link to the task to the editor, even if we want to block them from making changes.

**Comment by ajrbyers** [comment]
This was moved to the "Review Typesetting" link and is now always present.
