### ISSUE TITLE
Authors navigating to proofreading through dashboard are denied permission

### ISSUE THREAD

**Issue by joemull** [BirkbeckCTP/typesetting#164]
There is a bad link set in `templates/typesetting/elements/author_tasks.html` that causes authors to see a Permission denied message when they try to access proofreading assignments through the dashboard's article status page (e.g. `/dashboard/article/<article_id>/`). The link is for managing the task, rather than completing it.

**Comment by ajrbyers** [comment]
@joemull if this is an easy enough fix add it to: https://github.com/orgs/BirkbeckCTP/projects/10

**Comment by joemull** [comment]
@ajrbyers It is a very simple fix so I was going to fix it on #160 if that's all right.

**Comment by ajrbyers** [comment]
Ah I missed that this was the TS plugin. D'oh.
